version: '3.8'

services:
  feed-noticias:
    build: .
    container_name: feed-noticias
    restart: always
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.feed-noticias.rule=Host(`feed-noticias.srv1817339.hstgr.cloud`)"
      - "traefik.http.routers.feed-noticias.entrypoints=web,websecure"
      - "traefik.http.routers.feed-noticias.tls=true"
      - "traefik.http.routers.feed-noticias.tls.certresolver=letsencrypt"
      - "traefik.http.services.feed-noticias.loadbalancer.server.port=8501"
